course: "CS32"
qtr: "F18"
quarter: "Fall 2018"
piazza_url: https://piazza.com/ucsb/fall2018/cmpsc32/home
gauchospace_course_page: https://gauchospace.ucsb.edu/courses/course/view.php?id=31406
gradescope_class_url: https://www.gradescope.com/courses/25342

ta_list: "Sanjana, Yuke, and Aiwen"
ta_list_full: "Sanjana Sahayaraj, Yuke Wang, and Aiwen Xu"
mentors_list: "Carly Larsson, Xinyi Li, Arielle Robles, Zeyu Zhu"
discussion_section_times: "12pm, 1pm, 2pm, or 3pm"

github_url: https://github.com/ucsb-cs32-f18/ucsb-cs32-f18.github.io
mentor_url:

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048

start_week: 0
start_date: 2018-09-23 00:00:00.00-7:00
num_weeks: 11
extra_exam_week: true
sections: "12pm, 1pm, 2pm, 3pm"

cal_dates: >
  [
  {"label":"First day of Fall Quarter", "date":"2018-09-27" },
  {"label":"Veterans' Day", "date":"2018-11-12" },
  {"label":"Thanksgiving Break", "date":"2018-11-22" },
  {"label":"Thanksgiving Break", "date":"2018-11-23" },
  {"label":"Last day of instruction", "date":"2018-12-06" },
  {"label":"Finals Begin", "date":"2018-12-10" },
  {"label":"Finals End", "date":"2018-12-14" },
  {"label":"FINAL EXAM (4pm - 7pm)", "date":"2018-12-11" },
  {"label":"Last day to drop with fee", "date":"2018-10-18" }
  ]


kramdown:
   parse_block_html: true
   default_lang: python

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        

timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
